name: yelan
description: A demo application showing the potential of FP + caching.
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed: ^2.4.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  fpdart: ^1.1.0
  shared_preferences: ^2.2.1
  internet_connection_checker: ^1.0.0+1
  get_it: ^7.6.4
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  mobx_codegen: ^2.4.0
  provider: ^6.0.5
  flutter_svg: ^2.0.7
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/launcher.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - images/hydro.svg
    - images/pyro.svg
    - images/anemo.svg
    - images/electro.svg
    - images/dendro.svg
    - images/cryo.svg
    - images/geo.svg